export const SERVICE_CATEGORIES = [
  "Plumber",
  "Electrician",
  "Carpenter",
  "Painter",
  "AC Repair",
  "AC Installation",
  "Cleaning",
  "Deep Cleaning",
  "Bathroom Cleaning",
  "Kitchen Cleaning",
  "Sofa Cleaning",
  "Home Tutor",
  "Cook",
  "Driver",
  "Gardener",
  "Pest Control",
  "Appliance Repair",
  "TV Repair",
  "Refrigerator Repair",
  "Washing Machine Repair",
  "Microwave Repair",
  "RO Water Purifier Repair",
  "Water Purifier Installation",
  "CCTV Installation",
  "Computer Repair",
  "Laptop Repair",
  "Mobile Repair",
  "WiFi Installation",
  "Internet Setup",
  "Packers and Movers",
  "Furniture Assembly",
  "Furniture Repair",
  "Tile Work",
  "Masonry Work",
  "POP Work",
  "False Ceiling Work",
  "Interior Design",
  "Home Renovation",
  "Bathroom Renovation",
  "Kitchen Renovation",
  "Security Guard",
  "Babysitter",
  "Nanny",
  "Elder Care",
  "Laundry Service",
  "Ironing Service",
  "House Shifting Help",
  "Delivery Helper"
];
  
  export const INDIAN_CITIES = [
    "Pune"
  ];
  
  export const COMMON_AREAS = [
    // West Pune
    "Kothrud",
    "Warje",
    "Warje Malwadi",
    "Karve Nagar",
    "Bavdhan",
    "Pashan",
    "Sus",
    "Baner",
    "Balewadi",
    "Aundh",
    "Model Colony",
    "Erandwane",
    "Deccan",
    "Shivajinagar",
  
    // IT Belt
    "Hinjewadi",
    "Hinjewadi Phase 1",
    "Hinjewadi Phase 2",
    "Hinjewadi Phase 3",
    "Wakad",
    "Tathawade",
    "Punawale",
    "Mahalunge",
  
    // PCMC Areas
    "Pimpri",
    "Chinchwad",
    "Nigdi",
    "Akurdi",
    "Ravet",
    "Thergaon",
    "Kasarwadi",
    "Dapodi",
    "Sangvi",
    "Old Sangvi",
    "New Sangvi",
    "Pimple Saudagar",
    "Pimple Gurav",
    "Bhosari",
    "Moshi",
    "Chikhali",
    "Charholi",
    "Dighi",
    "Talawade",
    "Kiwale",
    "Dehu Road",
    "Alandi",
    "Borhade Wadi",
  
    // East Pune
    "Viman Nagar",
    "Kharadi",
    "Wagholi",
    "Lohegaon",
    "Dhanori",
    "Yerwada",
    "Kalyani Nagar",
    "Koregaon Park",
    "Mundhwa",
    "Magarpatta",
    "Hadapsar",
    "Manjri",
    "Phursungi",
  
    // South Pune
    "Kondhwa",
    "Kondhwa Budruk",
    "Kondhwa Khurd",
    "NIBM Road",
    "Undri",
    "Pisoli",
    "Wanowrie",
    "Fatima Nagar",
    "Bibwewadi",
    "Dhankawadi",
    "Katraj",
    "Ambegaon",
    "Ambegaon Budruk",
    "Sahakar Nagar",
    "Padmavati",
    "Parvati",
    "Gultekdi",
    "Market Yard",
  
    // Central Pune
    "Swargate",
    "Camp",
    "Sadashiv Peth",
    "Narayan Peth",
    "Shaniwar Peth",
    "Rasta Peth",
    "Somwar Peth",
    "Kasba Peth",
    "Budhwar Peth",
    "Ganesh Peth",
  
    // Sinhagad Road Belt
    "Sinhagad Road",
    "Vadgaon Budruk",
    "Anand Nagar",
    "Dhayari",
    "Narhe",
  
    // Additional Growing Areas
    "Keshav Nagar",
    "Handewadi",
    "Mohammadwadi",
    "Shewalewadi",
    "Uruli Devachi"
  ];

  // A Digital Marketplace for Reliable Local Services.